# Generated by Django 4.2.6 on 2023-12-11 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CallHistory",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("called_at", models.DateTimeField(auto_now_add=True)),
                ("numbers", models.CharField(max_length=50)),
                ("contents", models.TextField()),
                ("results", models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name="Organizations",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=20)),
                ("image", models.CharField(max_length=255)),
                ("call", models.CharField(max_length=50)),
                ("work", models.CharField(max_length=100)),
                ("url", models.CharField(max_length=255)),
                ("category", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="Text_KorCCVi",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("transcript", models.TextField()),
                ("label", models.BooleanField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Text_mail",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("message", models.TextField()),
                ("label", models.BooleanField(null=True)),
                ("phone_number", models.CharField(max_length=50, null=True)),
                ("message_embedding", models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="MFCC",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("mfcc", models.TextField()),
                (
                    "callhistory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="phishing.callhistory",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="mel_spectrograms",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "mel_spctrograms",
                    models.ImageField(null=True, upload_to="spectrograms/"),
                ),
                (
                    "callhistory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="phishing.callhistory",
                    ),
                ),
            ],
        ),
    ]
