# Generated by Django 4.2.6 on 2023-12-11 07:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("phishing", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mel_spectrograms",
            name="callhistory",
        ),
        migrations.RemoveField(
            model_name="mfcc",
            name="callhistory",
        ),
        migrations.AddField(
            model_name="mel_spectrograms",
            name="category",
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="mel_spectrograms",
            name="updated_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="mfcc",
            name="category",
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="mfcc",
            name="updated_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="callhistory",
            name="results",
            field=models.BooleanField(null=True),
        ),
    ]
