# Generated by Django 5.0 on 2023-12-11 10:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("phishing", "0002_remove_mel_spectrograms_callhistory_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="callhistory",
            name="audio_file",
            field=models.FileField(null=True, upload_to="audio/"),
        ),
        migrations.AlterField(
            model_name="callhistory",
            name="contents",
            field=models.TextField(null=True),
        ),
    ]
