# Generated by Django 5.0 on 2023-12-12 01:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("phishing", "0004_remove_mel_spectrograms_mel_spctrograms_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="mel_spectrograms",
            new_name="MelSpectrograms",
        ),
    ]
