# Generated by Django 5.0 on 2023-12-12 02:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("phishing", "0005_rename_mel_spectrograms_melspectrograms"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mfcc",
            name="mfcc",
            field=models.FileField(null=True, upload_to="mfcc/"),
        ),
    ]
